name: param
description: Simplifies changing/nullifying parameters for copyWith methods.
version: 0.0.1
homepage: https://github.com/rorystephenson/param

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
